import Footer from '../components/footer';
import Header from '../components/header';
import './global.css';

import { Providers } from './providers';

export const metadata = {
  title: 'Welcome to front-end',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
